package com.gantao.jfinal.model;

import com.gantao.jfinal.model.base.BaseBank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bank extends BaseBank<Bank> {
    public static final Bank dao = new Bank().dao();
}
