package com.gantao.jfinal.model;

import com.gantao.jfinal.model.base.BaseCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Customer extends BaseCustomer<Customer> {
	
}
