package com.gantao.jfinal.model;

import com.gantao.jfinal.model.base.BaseDeposite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Deposite extends BaseDeposite<Deposite> {
    public static final Deposite dao = new Deposite().dao();
}
