package com.gantao.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeposite<M extends BaseDeposite<M>> extends Model<M> implements IBean {

	public void setDId(java.lang.Integer dId) {
		set("d_id", dId);
	}
	
	public java.lang.Integer getDId() {
		return getInt("d_id");
	}

	public void setCId(java.lang.String cId) {
		set("c_id", cId);
	}
	
	public java.lang.String getCId() {
		return getStr("c_id");
	}

	public void setBId(java.lang.String bId) {
		set("b_id", bId);
	}
	
	public java.lang.String getBId() {
		return getStr("b_id");
	}

	public void setDepDate(java.util.Date depDate) {
		set("dep_date", depDate);
	}
	
	public java.util.Date getDepDate() {
		return get("dep_date");
	}

	public void setDepType(java.lang.String depType) {
		set("dep_type", depType);
	}
	
	public java.lang.String getDepType() {
		return getStr("dep_type");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

}
