package com.gantao.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomer<M extends BaseCustomer<M>> extends Model<M> implements IBean {

	public void setCId(java.lang.String cId) {
		set("c_id", cId);
	}
	
	public java.lang.String getCId() {
		return getStr("c_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setLocation(java.lang.String location) {
		set("location", location);
	}
	
	public java.lang.String getLocation() {
		return getStr("location");
	}

	public void setSalary(java.math.BigDecimal salary) {
		set("salary", salary);
	}
	
	public java.math.BigDecimal getSalary() {
		return get("salary");
	}

}
